<?php header( 'X-JSON: ({status: "Failed", message: "Resource is disabled for your level of access"})' ); ?>
<h1><span class="icon"><?php echo $this->img('/public/images/layout/icons/encrypted.png', array('alt' => 'Forbidden')); ?></span>Restricted resource<span class="describe">Insufficent access rights</span></h1>
<ul id="tabs">
	<li></li>
</ul>
<p>Resource is disabled for your level of access</p>