<?php if ($this->pageCount): ?> 
<div class="apple_pagination">
<div class="pagination">
<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
  <a href="<?= $this->url(array('page' => $this->previous)); ?>" class="prev_page" rel="prev start">« Previous</a>
<?php else: ?> 
  <span class="disabled prev_page">« Previous</span>
<?php endif; ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
    <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a> 
  <?php else: ?>
    <span class="current"><?= $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <a href="<?= $this->url(array('page' => $this->next)); ?>" class="next_page" rel="next">Next »</a>
<?php else: ?> 
  <span class="disabled next_page">Next »</span>
<?php endif; ?> 
</div>
</div>
<?php endif; ?>